### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by mathuin** [kihashi/stardew_community_checklist#100]
I would love to use this project, but there's no instructions on what to do.  Is it like SDV-Summary where I can run an instance in the cloud, then upload my saves?

I'm also interested in contributing to the project, but without knowing how to start the server and test it, I can't do much other than ask for docs. ;-)

**Comment by kihashi** [comment]
@mathuin Thanks for your interest! You've discovered this at something of a bad time. I'm currently working on a complete re-write of the project, so the documentation that previously existed is no longer correct and the new docs haven't been written yet (see #88). 

That said, it sounds like you found this by searching on Github? Most people are more interested in the [Live version](https://www.stardewcommunitychecklist.com) or the [beta version](https://kihashi.github.io/#/welcome). You might also want to check out the [subreddit](https://www.reddit.com/r/stardewchecklist/) I have set up for community-based discussion of it (since not everyone has a github account).

To address your specific questions:

> Is it like SDV-Summary where I can run an instance in the cloud, then upload my saves?

You *can* run your own instance in the cloud, but it's probably easier just to use the live versions mentioned above. There currently is no way to upload your save, but it's being investigated (see #64 ). 

> I'm also interested in contributing to the project, but without knowing how to start the server and test it, I can't do much other than ask for docs. ;-)

Well, there actually *is* a section on how to start a server in the readme, although it's no longer accurate with the re-write. You'll want to have npm/yarn installed and do

```
yarn install
yarn dev
```

I'm using Vuejs, Vue-router, and Vuex on the JS side and Bulma.io as CSS library.

Since we already have an issue about docs, I'm going to close this, but feel free to make additional comments if you have more questions.

**Comment by kihashi** [comment]
Here's the email I sent to another person who asked about the project that might be helpful:

> Thanks for your interest!
> 
> > which branch is the current build
> 
> The current live site is still running from Master, but I've been doing a re-write in the webpack branch. I had wanted to remove some code duplication using Vue single file components and after looking into them, I decided it made sense to just re-write from the ground up. Since a lot of things have changed (layout, data, etc), it doesn't make sense to continue development on the master branch.
> 
> Here's the tech that I am working with currently:
> 
> 1. Bulma CSS (https://bulma.io/)
> 2. Vuejs (https://vuejs.org/)
> 3. Vuex for state management (https://vuex.vuejs.org/en/)
> 4. Vue Router for routing (https://router.vuejs.org/en)
> 
> I have a demo site here: https://kihashi.github.io/
> 
> I started everything using the vue-cli and vue webpack template, so you might want to check those things out to get familiar with the project structure.
> 
> https://vuejs-templates.github.io/webpack/
> 
> Right now, I'm just working on getting feature parity with the live version. I still need to get
> 1. skill and season filtering
> 2. data persistence
> 3. Changelog
> 
> Most of the github issues are still valid. I've closed the ones that aren't.
> 
> Something that might be easier to get started with is either a function to convert the old saved data format to the new one (probably as a mutation in src/store/index.js) or to work on the inventory system (https://github.com/kihashi/stardew_community_checklist/issues/83). The changelog is also a piece that you could work on separately.
> 
> I can add some more detail in the issue for each of these things if there's anything that you'd like to work on in particular.
