### ISSUE TITLE
Season errors on Wheat and Sunflower

### ISSUE THREAD

**Issue by bladeoflight16** [kihashi/stardew_community_checklist#101]
The entry for Wheat says it's only available in Summer, and the entry for Sunflower says it's only available in Fall. But both can be grown in Summer and Fall. The Wiki confirms ([Wheat](https://stardewvalleywiki.com/Wheat), [Sunflower](https://stardewvalleywiki.com/Sunflower)), and I've grown Wheat in Fall myself.

**Comment by kihashi** [comment]
Thanks for the bug report!

In my defense, the wiki *used* to say otherwise (at least on the bundle page, where I pulled the data from): https://stardewvalleywiki.com/mediawiki/index.php?title=Bundles&oldid=28795

I'll try to make sure that it's fixed in the 2.0 update, which I hope to have out within the next few weeks.

**Comment by kihashi** [comment]
Sunflower is also fixed.
